Repository Tikhobaev/ProjectPI, pull requests merged in 2022-03, with the labels that each got.

#3 [Tests] Setup tests
  Podfile.lock
  WeatherMap.xcodeproj/project.pbxproj
  WeatherMap.xcodeproj/xcshareddata/xcschemes/WeatherMap.xcscheme
  WeatherMap/UI/Modules/BaseViewModel.swift
  WeatherMapTests/WeatherMapTests.swift
Labels: Tests

#5 [CI] Separate workflows
  .github/workflows/config_swift.yaml
Labels: CI

#6 [Docs] Added readme
  README.md
Labels: documentation
